% NETWORK SHAPES
NET=struct();
NET.SHAPE_SQUARE=0;
NET.SHAPE_C=1;
NET.SHAPE_RECTANGLE=2;
NET.SHAPE_L=3;
NET.SHAPE_LOOP=4;
NET.SHAPE_IRREGULAR=5;

% NODE PLACEMENT
NET.NODE_RANDOM=0;
NET.NODE_GRID=1;

% ANCHOR_PLACEMENT
NET.ANCHORS_CLUMPED=0;
NET.ANCHORS_CORNERS=1;
NET.ANCHORS_SPREAD=2;
NET.ANCHORS_RANDOM=3;

