subplot(2,3,1)
plot(network(:,1),network(:,2),'bo')
hold on
plot(network(anchor(1,1),1),network(anchor(1,1),2),'ro')
plot(network(anchor(1,2),1),network(anchor(1,2),2),'ro')
plot(network(anchor(1,3),1),network(anchor(1,3),2),'ro')
% plot(network(anchor(1,4),1),network(anchor(1,4),2),'ro')
% plot(network(anchor(1,5),1),network(anchor(1,5),2),'ro')
% plot(network(anchor(1,6),1),network(anchor(1,6),2),'ro')
subplot(2,3,2)
plot(network(:,1),network(:,2),'bo')
hold on
plot(network(anchor(2,1),1),network(anchor(2,1),2),'ro')
plot(network(anchor(2,2),1),network(anchor(2,2),2),'ro')
plot(network(anchor(2,3),1),network(anchor(2,3),2),'ro')
% plot(network(anchor(2,4),1),network(anchor(2,4),2),'ro')
% plot(network(anchor(2,5),1),network(anchor(2,5),2),'ro')
% plot(network(anchor(2,6),1),network(anchor(2,6),2),'ro')
subplot(2,3,3)
plot(network(:,1),network(:,2),'bo')
hold on
plot(network(anchor(3,1),1),network(anchor(3,1),2),'ro')
plot(network(anchor(3,2),1),network(anchor(3,2),2),'ro')
plot(network(anchor(3,3),1),network(anchor(3,3),2),'ro')
% plot(network(anchor(3,4),1),network(anchor(3,4),2),'ro')
% plot(network(anchor(3,5),1),network(anchor(3,5),2),'ro')
% plot(network(anchor(3,6),1),network(anchor(3,6),2),'ro')
subplot(2,3,4)
plot(network(:,1),network(:,2),'bo')
hold on
plot(network(anchor(4,1),1),network(anchor(4,1),2),'ro')
plot(network(anchor(4,2),1),network(anchor(4,2),2),'ro')
plot(network(anchor(4,3),1),network(anchor(4,3),2),'ro')
% plot(network(anchor(4,4),1),network(anchor(4,4),2),'ro')
% plot(network(anchor(4,5),1),network(anchor(4,5),2),'ro')
% plot(network(anchor(4,6),1),network(anchor(4,6),2),'ro')
subplot(2,3,5)
plot(network(:,1),network(:,2),'bo')
hold on
plot(network(anchor(5,1),1),network(anchor(5,1),2),'ro')
plot(network(anchor(5,2),1),network(anchor(5,2),2),'ro')
plot(network(anchor(5,3),1),network(anchor(5,3),2),'ro')
% plot(network(anchor(5,4),1),network(anchor(5,4),2),'ro')
% plot(network(anchor(5,5),1),network(anchor(5,5),2),'ro')
% plot(network(anchor(5,6),1),network(anchor(5,6),2),'ro')
% subplot(3,3,6)
% plot(network(:,1),network(:,2),'bo')
% hold on
% plot(network(anchor(6,1),1),network(anchor(6,1),2),'ro')
% plot(network(anchor(6,2),1),network(anchor(6,2),2),'ro')
% plot(network(anchor(6,3),1),network(anchor(6,3),2),'ro')
% subplot(3,3,7)
% plot(network(:,1),network(:,2),'bo')
% hold on
% plot(network(anchor(7,1),1),network(anchor(7,1),2),'ro')
% plot(network(anchor(7,2),1),network(anchor(7,2),2),'ro')
% plot(network(anchor(7,3),1),network(anchor(7,3),2),'ro')
% subplot(3,3,8)
% plot(network(:,1),network(:,2),'bo')
% hold on
% plot(network(anchor(8,1),1),network(anchor(8,1),2),'ro')
% plot(network(anchor(8,2),1),network(anchor(8,2),2),'ro')
% plot(network(anchor(8,3),1),network(anchor(8,3),2),'ro')
% subplot(3,3,9)
% plot(network(:,1),network(:,2),'bo')
% hold on
% plot(network(anchor(9,1),1),network(anchor(9,1),2),'ro')
% plot(network(anchor(9,2),1),network(anchor(9,2),2),'ro')
% plot(network(anchor(9,3),1),network(anchor(9,3),2),'ro')